version: '3'
services:
  db_postgres:
    container_name: db_prod_postgres
    image: postgres:11.1-alpine
    volumes:
      - 'vol_data_podtgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=db_prod
      - POSTGRES_USER=user_prod
      - POSTGRES_PASSWORD=pass_prod
  app_netflix:
    container_name: app_netflix
    image: com.at/netflix
    ports:
      - 8080:8080
    depends_on:
      - db_postgres
      - redis_server
    environment:
      - DATABASE_HOST=db_postgres
      - DATABASE_PORT=5432
      - DATABASE_DB=db_prod
      - DATABASE_USER=user_prod
      - DATABASE_PASSWORD=pass_prod
  redis_server:
    container_name: redis_container
    image: redis
    volumes:
      - 'redis_vol:/data'
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes
volumes:
  vol_data_podtgres:
  redis_vol:






